---
name: simplex_advanced
version: "0.1"
dependencies:
  - scipy>0.18
params:
  start_from_current: True
  x0: [0, 0]
  scan_params_name: scan32-RCDS_scan_w_precision_from_sim_hess_correctedfactor2
  xtol: 1.0e-05
  max_iter: 100
